# install and config nginx

- name: install nginx
  apt: 
    name: nginx 
    state: latest
    update_cache: yes
  notify: active_nginx


- name: copy nginx configurations
  ansible.builtin.template:
    src: var/www/nginx/sites-enabled/nginx.conf.j2
    dest: "/var/www/nginx/sites-enabled/{{ site.doamin }}"
  with_item: "{{ list_sites }}"
  notify: restart_nginx

